// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma
import { defineConfig } from "prisma/config";


// create a .env file and put DATABASE_URL="file:./database.db"
export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: process.env["DATABASE_URL"],
  },
});
